spring:
  application:
    name: yufesta

  profiles:
    default: dev

  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
